### ISSUE TITLE
Infrastructure Design/Brainstorm for nmap-agent

### ISSUE THREAD

**Issue by claudijd** [mozilla/nmap-agent#1]
Here's an example of how this could conceivably work...

![image](https://user-images.githubusercontent.com/794283/42890322-846ddaee-8a7a-11e8-8ba2-f713cff7f9a1.png)

**Comment by ajvb** [comment]
@claudijd This looks great. Read through the code and +1 all the way.

One thought that I'd like to put out there early is: Creating a `moz-security-shared` or similar AWS account for this service and potentially others. Would be nice to have an AWS account that has limited users and is hardened that can be used for collaborating on projects across the various Mozilla security teams.

**Comment by Gutopro** [comment]
hello @claudijd I read through the README, and I must say this is a really interesting project, which I would like to contribute to as I am new to opensource. The title of the Issue is "Infrastructure Design/Brainstorm for Nmap-agent", I understand as per the image above that you would like suggestions on how to improve the infrastructure design and at that I am very much willing to help, if it doesn't bother you could you please bring me up to speed with the project, what you  would like me to do  and how to go about it? thank you and hope to hear from you.
